import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { BsCalendar2Week as CalendarIcon  } from "react-icons/bs";
import { BiBuildingHouse as FiisIcon  } from "react-icons/bi";
import { AiOutlineHome as HomeIcon } from "react-icons/ai";

import Logo from '../components/logo';
import SearchInput from '../components/searchInput';
import Anchor from '../components/anchor';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sr. Barriga FIIs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <Logo />          
          <div className={styles.mainMenu}>
            <Anchor href="/" linkIcon={HomeIcon}  linkText="inicio" />
            <Anchor href="#" linkIcon={CalendarIcon} linkText="agenda dividendos" />
            <Anchor href="/allfiis" linkIcon={FiisIcon}  linkText="todos FIIs" />
            <SearchInput />
          </div>
        </div>

        <section className={styles.content}>
        <section className={styles.contentFiis}>
            <h3>Todos Fiis</h3>   
            <div className={styles.indicatorsFii}>
            </div>
        </section>
        </section>
        
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
