import type { NextPage } from 'next';
import { useEffect, useState } from 'react';
import axios from 'axios';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { BsCalendar2Week as CalendarIcon  } from "react-icons/bs";
import { BiBuildingHouse as FiisIcon  } from "react-icons/bi";
import { AiOutlineHome as HomeIcon } from "react-icons/ai";

import Logo from '../components/logo';
import SearchInput from '../components/searchInput';
import Anchor from '../components/anchor';

type TickersPrices = {
    ticker_price_id: string
    ticker: string
    ticker_date: Date
    ticker_price_close: number
    ticker_price_open: number
    ticker_price_high: number
    ticker_price_low: number
    ticker_price_volume: number
    updated_at: Date,
    gain: number
}

type TickersPricesResponse = {
  total: number,
  prices: TickersPrices[]

}

const AllFiis: NextPage = () => {

  const [fiisPrice, setFiisPrice] = useState<TickersPrices[]>();
  const [loadingPage, setLoadingPage] = useState<boolean>(true);

  useEffect(() => {
    async function getFiisPrices () {
      const requesteResponse = await axios.get(`/api/ticker/price`);
      const getData: TickersPricesResponse = await requesteResponse.data;
      return getData;
    }
    getFiisPrices().then((fiisData) => {
      fiisData.prices.sort((a ,b) => {
        if(a.gain > b.gain){
          return -1;
        }
        return 1;
      });
      setFiisPrice(fiisData.prices);
      setLoadingPage(false);
    }).catch(error => {
      console.log(error);
    })
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Sr. Barriga FIIs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <Logo />
          <div className={styles.mainMenu}>
            <Anchor href="/" linkIcon={HomeIcon} linkText="inicio" />
            <Anchor href="#" linkIcon={CalendarIcon} linkText="agenda dividendos" />
            <Anchor href="/allfiis" linkIcon={FiisIcon} linkText="todos FIIs" />
            <SearchInput />
          </div>
        </div>

        <section className={styles.content}>

          <section className={styles.contentFiis}>
            <h3>Todos Fiis  </h3>
            <div className={styles.indicatorsFii}>
            { loadingPage ? <span className={styles.loadingPage}>carregando </span> : 
              <table className={styles.allFiisTable}>
                <thead>
                  <tr>
                    <td><span>#</span></td>
                    <td><span>ticker</span></td>
                    <td><span>date price</span></td>
                    <td><span>price</span></td>
                    <td><span>gain</span></td>
                    <td><span>volume</span></td>
                    <td><span>update at</span></td>
                  </tr>
                </thead>
                <tbody>
                  
                {fiisPrice && fiisPrice.map((data, index) => (
                  <tr key={index}>
                    <td>{index + 1}</td>
                    <td>{data.ticker}</td>
                    <td>{data.ticker_date}</td>
                    <td>R$ {data.ticker_price_close}</td>
                    <td>{data.gain}%</td>
                    <td>{data.ticker_price_volume}</td>
                    <td>{data.updated_at}</td>
                  </tr>
                ))}
                </tbody>
              </table> }

            </div>
        </section>
      </section>

    </main>
    </div>
  )
}




export default AllFiis;
