import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Logo from '../components/logo';
import SearchInput from '../components/searchInput';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sr. Barriga FIIs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <Logo />          
          <div className={styles.mainMenu}>
            <SearchInput />
          </div>
        </div>
        
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
