name: ticker-price-update
on: 
  schedule:
    - cron: '* 5 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: run-job
        run: curl --request POST https://srbarrigafiis.vercel.app/api/ticker/update
